; Exercise 2.41: Write a procedure to find all ordered triples of distinct positive integers i, j, and k less than or equal to a given integer n that sum to a given integer s.
(define nil '())
(define (enumerate low high)
  (if (> low high)
        nil
        (cons low (enumerate (+ low 1) high))))
(load "flatmap.scm")
(define (ordered-triples n s)
  (filter (lambda (t) (= (+ (car t) (cadr t) (cadr (cdr t))) s))
          (flatmap (lambda (i)
                    (flatmap (lambda (j)
                      (map (lambda (k)
                              (list i j k)) 
                            (enumerate 1 (- j 1))))
                          (enumerate 1 (- i 1))))
                  (enumerate 1 n))))